### ISSUE TITLE
Confirm license that applies to material we publish

### ISSUE THREAD

**Issue by myitcv** [go-london-user-group/admin#18]
We should clarify on our website/here the license that applies the material that we publish, including our main slide deck, YouTube videos, conundrums etc.

**Comment by domgreen** [comment]
What are the thoughts around this? Do we have strong opinions? 

I think this repo at least should be permissive as we are wanting to share and allow others to learn.

**Comment by myitcv** [comment]
My base assumption on this is to go with https://github.com/golang/go/blob/master/LICENSE

But open to other ideas.

**Comment by domgreen** [comment]
I'm not too fussed tbh but what does that license mean? We are not just doing source code/binaries... and we don't have a copyright on anything.

Would that one be the choice as it's from the Go language? I don't feel we need to have the same but something that makes sense for our content presentations, docs around meetups, videos, conundrums etc.

**Comment by myitcv** [comment]
We are creating content here, so there is a copyright on what we create. By licensing it we are making clear how other people can use the content we create. 

Perhaps creative commons is more appropriate?

https://golang.org/doc/copyright.html

**Comment by domgreen** [comment]
I think I prefer Creative Commons ... it is clearer to me what is allowed / should be done on reuse/modification of the content.

**Comment by domgreen** [comment]
If we went with that I think our LICENSE file would jsut be:
```
This work is licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by/3.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
```

**Comment by domgreen** [comment]
Address and agreed in #31
